version: 1.2
workflows:
  - subclass: <WDL>
    primaryDescriptorPath: 
    testParameterFiles:
    readMePath: README.md
    authors:
      - name: Jacob Lemieux
        email: lemieux@broadinstitute.org
    topic: bwa
