version: 1.2
workflows:
  - subclass: WDL
    primaryDescriptorPath: wdl/mapbwa.wdl 
    readMePath: wdl/README.md
    authors:
      - name: Jacob Lemieux
        email: lemieux@broadinstitute.org
    topic: genome alignment
